# Generated by Django 2.2.4 on 2020-07-25 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200724_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(upload_to='category_img')),
                ('slug', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1200)),
                ('image', models.ImageField(upload_to='product_image')),
                ('real_price', models.IntegerField()),
                ('dicount_price', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('publish', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
