# Generated by Django 2.2.4 on 2020-07-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200725_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='dicount_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='real_price',
        ),
    ]
